name: Deploy promo.nerp.app
on: { push: { branches: [ "main" ] } }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo git config --system --add safe.directory /var/www/promo.nerp.app
            sudo -u www-data env GIT_SSH_COMMAND='ssh -i /var/www/.ssh/gh_promodeploy -o StrictHostKeyChecking=no' bash -lc '
              cd /var/www/promo.nerp.app
              git reset --hard
              git pull origin main
            '
            sudo chown -R www-data:www-data /var/www/promo.nerp.app
            sudo systemctl reload apache2
